# Football Transfer Prediction Configuration

# 데이터 경로
data:
  raw_dir: "data/raw"
  curated_dir: "data/curated"
  processed_dir: "data/processed"
  output_dir: "outputs"

# 피처 설정
features:
  target_column: "transfer"
  ordinal_features: ["season"]
  nominal_features:
    ["club_name", "country_of_birth", "foot", "position", "sub_position"]

  # 고급 피처 (8개)
  advanced_features:
    - "minutes_vs_club_avg"
    - "age_difference"
    - "attack_contribution"
    - "is_foreigner"
    - "height_vs_position"
    - "cards_per_minute"
    - "club_tenure_seasons"
    - "position_competition"

# 모델 설정
model:
  test_season: "22/23"
  prediction_season: "23/24"
  random_state: 42
  cv_folds: 5

  # 모델 목록
  models:
    - name: "Logistic Regression"
      class: "LogisticRegression"
      params:
        random_state: 42
        class_weight: "balanced"

    - name: "Random Forest"
      class: "RandomForestClassifier"
      params:
        random_state: 42
        class_weight: "balanced"

    - name: "XGBoost"
      class: "XGBClassifier"
      params:
        random_state: 42
        eval_metric: "logloss"

# 평가 지표
evaluation:
  composite_score_weights:
    auc: 0.4
    f1: 0.3
    precision: 0.2
    recall: 0.1

  # 하이퍼파라미터 튜닝
  hyperparameter_tuning:
    enabled: true
    models: ["Random Forest"]
    param_grids:
      Random Forest:
        n_estimators: [50, 100, 200]
        max_depth: [10, 20, 30, null]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]

# SHAP 설정
shap:
  enabled: true
  sample_size: 1000
  max_display: 15

# 로깅 설정
logging:
  level: "INFO"
  file: "logs/football_prediction.log"
